### ISSUE TITLE
Release Checklist - v1.0.0

### ISSUE THREAD

**Issue by TonyGrif** [TonyGrif/producer-consumer#1]
Features required to make this repo public

## Build
- [ ] Utilize Jenkins for CI testing and linting
- [ ] Utilize Jenkins to build and publish the Jar file on Git tag
- [ ] Remove samples
- [ ] Update gradle version
- [ ] Update packages
- [ ] Remove jar file from git

## App
- [ ] Break producer and consumer classes into their own, tested classes
- [ ] Update consumer message to show which buffer is consumed
- [ ] Break apart library and script

## Documentation
- [ ] Published Javadoc API
- [ ] Create quick doc site for running instructions
